version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: smart-oa-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: smart_oa
      MYSQL_USER: smartoa
      MYSQL_PASSWORD: smartoa123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - smart-oa-network

  # Redis缓存
  redis:
    image: redis:6.2-alpine
    container_name: smart-oa-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-oa-network

  # MinIO文件存储
  minio:
    image: minio/minio:latest
    container_name: smart-oa-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - smart-oa-network

  # 后端应用
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: smart-oa-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_oa?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: smartoa
      SPRING_DATASOURCE_PASSWORD: smartoa123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - mysql
      - redis
      - minio
    networks:
      - smart-oa-network

  # 前端应用
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: smart-oa-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - smart-oa-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: smart-oa-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - smart-oa-network

volumes:
  mysql_data:
  redis_data:
  minio_data:

networks:
  smart-oa-network:
    driver: bridge 