# 生产环境配置文件
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: smart-oa-backend
  
  # 生产环境数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/smart_oa?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # 生产环境连接池配置
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 300000
      pool-name: SmartOAHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # JPA配置 - 生产环境
  jpa:
    hibernate:
      ddl-auto: validate  # 生产环境不自动创建表
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false  # 生产环境不显示SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        
  # Redis配置
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1ms
        max-idle: 10
        min-idle: 5

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# JWT配置 - 生产环境使用环境变量
app:
  jwt:
    secret: ${JWT_SECRET:smartOASecretKeyForJWTTokenGeneration2025}
    expiration: 86400000 # 24小时（毫秒）

# 日志配置 - 生产环境
logging:
  level:
    com.smartoa: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/smart-oa.log
    max-size: 100MB
    max-history: 90

# 管理端点配置 - 生产环境限制
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# 生产环境自定义配置
smartoa:
  # 系统配置
  system:
    name: Smart OA 智能办公系统
    version: 2.0.0
    description: 基于Spring Boot + Vue的智能办公自动化系统
    environment: production
    
  # 安全配置 - 生产环境严格
  security:
    # 忽略认证的URL - 最小化
    ignore-urls:
      - /api/auth/login
      - /actuator/health
      - /favicon.ico
      - /error
    
    # 密码策略 - 生产环境更严格
    password:
      min-length: 8
      max-length: 20
      require-uppercase: true
      require-lowercase: true
      require-digit: true
      require-special: true
      
  # 文件存储配置
  file:
    upload-path: /var/smartoa/uploads/
    allowed-types: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt
    max-size: 10MB
    
  # 邮件配置
  mail:
    enabled: ${MAIL_ENABLED:false}
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:}
    
  # 短信配置
  sms:
    enabled: ${SMS_ENABLED:false}
    provider: aliyun
    access-key: ${SMS_ACCESS_KEY:}
    secret-key: ${SMS_SECRET_KEY:}
    sign-name: ${SMS_SIGN_NAME:}
    template-code: ${SMS_TEMPLATE_CODE:}

# 生产环境安全警告
---
# 重要：生产环境部署前请确保：
# 1. 修改默认的JWT密钥
# 2. 设置强密码的数据库用户
# 3. 配置正确的Redis连接
# 4. 设置适当的文件上传路径
# 5. 配置HTTPS
# 6. 设置防火墙规则 