server:
  port: 8080

spring:
  application:
    name: smart-oa-minimal
  
  # Disable database for minimal version
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging:
  level:
    com.smartoa: DEBUG
    org.springframework.security: DEBUG 