# 开发环境配置
server:
  port: 8080

spring:
  # 使用H2内存数据库进行开发测试
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
    # H2控制台配置
    h2:
      console:
        enabled: true
        path: /h2-console
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        
  # 禁用Redis（开发环境）
  redis:
    enabled: false

# 日志配置
logging:
  level:
    com.smartoa: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 安全配置
smartoa:
  security:
    ignore-urls:
      - /api/auth/**
      - /api/public/**
      - /h2-console/**
      - /swagger-ui/**
      - /v3/api-docs/**
      - /actuator/health
      - /favicon.ico
      - /error 